### ISSUE TITLE
Error: Permission to perform this operation was denied

### ISSUE THREAD

**Issue by matteu31400** [vmware-samples/packer-examples-for-vsphere#337] opened 2022-11-07 21:52 UTC
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

22.09 (latest)

### VMware vSphere

7.0.3

### HashiCorp Packer

1.8.4

### HashiCorp Packer Plugin for VMware vSphere

1.1.0

### Guest Operating System

Debian 11

### Environment Details

Debian 11

### Description

I try to build W10 and W11 image but I have permission error

### Expected Behavior

```console
Build 'vsphere-iso.windows-desktop' errored after 1 second 513 milliseconds: ServerFaultCode: Permission to perform this operation was denied.
```

### Actual Behavior

```console
==> vsphere-iso.windows-desktop: Uploading packer2654841596.iso to packer_cache/packer2654841596.iso
==> vsphere-iso.windows-desktop: Creating VM...
==> vsphere-iso.windows-desktop: Customizing hardware...
==> vsphere-iso.windows-desktop: Destroying VM...
==> vsphere-iso.windows-desktop: Deleting cd_files image from remote datastore ...
Build 'vsphere-iso.windows-desktop' errored after 1 second 513 milliseconds: ServerFaultCode: Permission to perform this operation was denied.
```

### Steps to Reproduce

Use terraform file to create packer role on vcenter and assign it to a user on global permission vcenter
Use this user to deploy W10 or W11 image.

There is no issue for W2019 or 2022

**Comment by tenthirtyam** [comment] 2022-11-08 02:41
Duplicate of #293

**Comment by tenthirtyam** [comment] 2022-11-08 02:54
Likely a duplicate on #293.

**Closed** 2022-11-08 16:28 UTC
Labels: type/bug, status/needs-triage
