### ISSUE TITLE
Unable to deploy Debian 12.4 image using Terraform

### ISSUE THREAD

**Issue by OlsenOliver** [vmware-samples/packer-examples-for-vsphere#815] opened 2024-01-23 16:50 UTC
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.0

### HashiCorp Packer Plugin for VMware vSphere

1.2.3

### Guest Operating System

Ubuntu Server 22.04 LTS

### Environment Details

Ubuntu 22.04 LTS running Packer and Terraform. I have created a template using Packer based on the debian-12.4-amd64-netinst.iso (cannot seem to find 12.2). I am unable to deploy this OVF-template using the included Terraform files (from the content-library-ovf-linux-guest-customization folder).

### Description

I am using the included Terraform code (content-library-ovf-linux-guest-customization folder) to deploy a Debian 12.4 OVF template I created using Packer, based on this repo. I did not change anything but items related to my vSphere environment, so a clean build. Doing the normal procedures with Terraform
```
terraform init
terraform plan
terraform apply
```
It consistently fails with this message
```
 Error: error sending customization spec: Customization of the guest operating system is not supported due to the given reason:
│
│   with vsphere_virtual_machine.vm,
│   on main.tf line 42, in resource "vsphere_virtual_machine" "vm":
│   42: resource "vsphere_virtual_machine" "vm" {
```
From previous TF deployments with Debian I have experienced trouble with the "vm_guest_os_type" variable. I tried substituting "other5xLinux64Guest" with "debian11_64Guest", "ubuntu64Guest" and "otherLinux64Guest" without success. Surely open-vm-tools was installed on the template, so I'm out of ideas. 

I tried this on two different vSphere clusters (both vSphere 7.0.3.01700/ESXi 7.0.3.22348816) with similar results. I tried building OVF-templates from Oracle Linux 8.9/9.3 as well as Ubuntu 22.04-3 - all deployed successfully.

Not sure where to start looking for the actual root cause, so any input is of great value!

### Expected Behavior

Expected that the vm_guest_os_type variable included in the example files worked, and a successful deployment.

### Actual Behavior

Ubuntu 12.4 fails to deploy with Terraform

### Steps to Reproduce

Clean install of Ubuntu 22.04-03LTS and the requirements from Hashicorp.

**Comment by tenthirtyam** [comment] 2024-01-23 17:08
Can you confirm if the result is the same with Debian 11?

**Comment by tenthirtyam** [comment] 2024-01-23 17:12
Also, can you confirm that a manual deployment of the image comes online w/o customization and confirm the guests label that is detected?

**Comment by OlsenOliver** [comment] 2024-01-23 19:43
> Can you confirm if the result is the same with Debian 11?

I just tried using the default Debian 11 template, and it did not go through having the same errors. Checking vCenter is says "The Guest 'OS Debian GNU/Linux 11 (64bit)' installed in the VM is not supported for customization.

**Comment by tenthirtyam** [comment] 2024-01-23 21:15
I know what the issue is - will need to add a workaround in Ansible to force the version to `other5xLinux64Guest`.

I'll take a look in due course.

**Comment by OlsenOliver** [comment] 2024-01-23 21:43
> I know what the issue is - will need to add a workaround in Ansible to force the version to `other5xLinux64Guest`.
> 
> I'll take a look in due course.

Your efforts are highly appreciated :-)  I know I could use Ubuntu for most of the planned Debian servers, but given the recent changes with eg RedHat I feel DEbian is the safer choice right now. Fingers crossed. If you need any more information, please let me know and I'll try to add it as soon as time permits.
Thanks!

**Comment by tenthirtyam** [comment] 2024-01-26 18:57
Can you dd the following to the end of `ansible/roles/configure/tasks/debian.yml`, rebuild the template as an OVA, and try the customization again?

```yaml
- name: "Setting guest operating system information."
  blockinfile:
    path: /etc/vmware-tools/tools.conf
    block: |
      [guestosinfo]
      short-name = other5xLinux64Guest
    create: true
  when: ansible_distribution == 'Debian'
```

**Comment by OlsenOliver** [comment] 2024-01-27 08:40
> Can you add the following to the end of `ansible/roles/configure/tasks/debian.yml`, rebuild the template as an OVA, and try the customization again?
> 
> ```yaml
> - name: "Setting guest operating system information."
>   blockinfile:
>     path: /etc/vmware-tools/tools.conf
>     block: |
>       [guestosinfo]
>       short-name = other5xLinux64Guest
>     create: true
>   when: ansible_distribution == 'Debian'
> ```
> 
> Ref: [#195 (comment)](https://github.com/vmware-samples/packer-examples-for-vsphere/pull/195#issuecomment-1219932995)
> 
> This should force VMTools to see it as Other Linux 5.x kernel and not detect Debian.

I tried this last night with the develop-repo I cloned on Jan 17th, but no luck. The changes in the ansible-file was surely reflected in /etc/vmtware-tools/tools.conf when i tried deploying the OVA manually, so I have no idea why it still failed with the same errors.

However, I decided to try from a freshly cloned develop-repo a few minutes ago, applied the suggested changes in the ansible-file, and voila :-)

`Apply complete! Resources: 1 added, 0 changed, 0 destroyed.`

Thanks a lot for your great efforts!

**Comment by tenthirtyam** [comment] 2024-01-27 13:11
Thanks for confirming, I'll get this merged in soon.

**Closed** 2024-01-27 13:36 UTC
Labels: type/bug, status/awaitng-response
